# Generated by Django 3.1.2 on 2020-10-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-published_date']},
        ),
    ]
