# Generated by Django 3.1.2 on 2020-10-21 07:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20201021_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
