# Generated by Django 3.1.3 on 2020-11-20 07:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20201120_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=6000),
        ),
    ]
