# Generated by Django 3.1.3 on 2020-11-28 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0015_auto_20201120_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='flags',
            field=models.ManyToManyField(blank=True, related_name='flags', to=settings.AUTH_USER_MODEL),
        ),
    ]
