# Generated by Django 3.1.4 on 2020-12-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_reply_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
