# Generated by Django 3.1.4 on 2020-12-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20201203_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='is_lockedd',
            new_name='is_locked',
        ),
    ]
