# Generated by Django 3.1.4 on 2020-12-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20201203_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
