# Generated by Django 3.1.2 on 2020-10-25 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('about_me', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('favourite_anime', models.CharField(blank=True, max_length=100)),
                ('favourite_genres', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Historical', 'Historical'), ('Sci-fi', 'Sci-fi'), ('Seinen', 'Seinen'), ('Shounen', 'Shounen'), ('Mystery', 'Mystery'), ('Ecchi', 'Ecchi'), ('Sports', 'Sports'), ('Psychological', 'Psychological'), ('Supernatural', 'Supernatural')], max_length=113)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
