# Generated by Django 3.1.2 on 2020-10-30 11:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20201030_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_anime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_genres',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Historical', 'Historical'), ('Sci-fi', 'Sci-fi'), ('Seinen', 'Seinen'), ('Shounen', 'Shounen'), ('Mystery', 'Mystery'), ('Ecchi', 'Ecchi'), ('Sports', 'Sports'), ('Psychological', 'Psychological'), ('Supernatural', 'Supernatural')], max_length=113, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/img/avatar.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
