# Generated by Django 3.1.2 on 2020-11-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20201030_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/avatar.png', null=True, upload_to='users/'),
        ),
    ]
