# Generated by Django 3.1.3 on 2020-11-22 10:23

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20201113_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='avatar.png', null=True, upload_to='users/'),
        ),
    ]
