# Generated by Django 3.1.4 on 2020-12-09 08:06

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20201122_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='avatar.jpg', null=True, upload_to='users/'),
        ),
    ]
